## Spring Application
#spring.application.name=Haus
#spring.profiles.active=dev
#
## Server
#server.port=8080
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#
## Application
#application.repository.query-limit-warning-ms=300
#
## Database
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/haus?createDatabaseIfNotExist=true}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
##spring.jpa.show-sql=true
#spring.jpa.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.use_sql_comments=true
#
## SendGrid Email
#spring.sendgrid.api-key=${SENDGRID_API_KEY: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}
#spring.sendgrid.from-email=quanducbui2017@gmail.com
#spring.sendgrid.template-registration-id=d-3bda4951dfac403f8d1ec196d9c1c800
#spring.sendgrid.template-forgot-id=d-ef1fae82216744d193b7c7657a5912a3
#spring.sendgrid.image-prev=https://res.cloudinary.com/dgwnoquie/image/upload/v1755789933/image-43_f3kmgh.jpg
#spring.sendgrid.image-next=https://res.cloudinary.com/dgwnoquie/image/upload/v1755790009/KHACH-BEP-15_bj8u43.jpg
#spring.sendgrid.logo=https://res.cloudinary.com/dgwnoquie/image/upload/v1755791051/HAUS-logo_byhum7.jpg
#
## SpringDoc OpenAPI
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#
## OpenAPI
#openapi.service.api-docs=Haus
#openapi.service.server=http://localhost:${server.port:8080}
#openapi.service.title=${API_TITLE:DUMMY API TITLE}
#openapi.service.version=v1.0.0
#
## Security Endpoints
#security.public-endpoints=/oauth2/**, /auth/**
#security.user-endpoints=/user/**
#security.admin-endpoints=/admin/**
#security.swagger-endpoints=/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html
#
## JWT
#jwt.expiryHour=1
#jwt.expiryDay=1
#jwt.accessKey=c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
#jwt.refreshKey=9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=
#
## Cloudinary
#cloudinary.cloud_name=${CLOUDINARY_NAME}
#cloudinary.api_key=${CLOUDINARY_API_KEY}
#cloudinary.secret_key=${CLOUDINARY_SECRET_KEY}
