spring:
  config:
    activate:
      on-profile: prod

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API DOCUMENT
    version: v1.0.0

rate-limit:
  enabled: true
  storage-type: redis
  whitelist-ips:
    - 127.0.0.1
  default:
    capacity: 500
    refill-tokens: 500
    refill-duration: PT1H
  per-ip:
    capacity: 100
    refill-tokens: 100
    refill-duration: PT10M
  endpoints:
    - path: /api/v1/auth/login
      capacity: 5
      refill-tokens: 5
      refill-duration: PT1M
      by-ip: true
    - path: /api/v1/auth/register
      capacity: 5
      refill-tokens: 5
      refill-duration: PT1H
      by-ip: true
    - path: /api/v1/auth/forgot-password
      capacity: 3
      refill-tokens: 3
      refill-duration: PT5M
      by-ip: true
    - path: /api/v1/auth/verify-otp
      capacity: 5
      refill-tokens: 5
      refill-duration: PT5M
      by-ip: true
    - path: /api/v1/auth/verify-otp-to-reset-password
      capacity: 5
      refill-tokens: 5
      refill-duration: PT5M
      by-ip: true
    - path: /api/v1/auth/reset-password
      capacity: 3
      refill-tokens: 3
      refill-duration: PT5M
      by-ip: true
    - path: /api/v1/auth/refresh
      capacity: 20
      refill-tokens: 20
      refill-duration: PT1M
      by-ip: false

    - path: /api/v1/user/update-password
      capacity: 3
      refill-tokens: 3
      refill-duration: PT10M
      by-ip: false
    - path: /api/v1/user/delete-my-account
      capacity: 2
      refill-tokens: 2
      refill-duration: PT1H
      by-ip: false

    - path: /api/v1/payment/vnpay/payment_url
      capacity: 5
      refill-tokens: 5
      refill-duration: PT1M
      by-ip: false
    - path: /api/v1/payment/momo/create
      capacity: 5
      refill-tokens: 5
      refill-duration: PT1M
      by-ip: false
    - path: /api/v1/payment/cod
      capacity: 5
      refill-tokens: 5
      refill-duration: PT1M
      by-ip: false

    - path: /api/v1/product/search
      capacity: 50
      refill-tokens: 50
      refill-duration: PT1M
      by-ip: true