## Spring Application
#spring.application.name=Haus
#spring.profiles.active=dev
#
## Server
#server.port=8080
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#
## Application
#application.repository.query-limit-warning-ms=300
#
## Database
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/haus?createDatabaseIfNotExist=true}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## JPA / Hibernate
##spring.jpa.show-sql=true
#spring.jpa.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.use_sql_comments=true
#
## SendGrid Email
#spring.sendGrid.apiKey=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
#spring.sendGrid.fromEmail=nguyencuong291.work@gmail.com
#spring.sendGrid.templateRegistrationId=d-e931779d79b1497099e3c305451eca54
#spring.sendGrid.templateForgotId=d-ce282bb8535349968d3ccc242c8d57ab
#spring.sendGrid.imagePrev=https://res.cloudinary.com/dgwnoquie/image/upload/v1755789933/image-43_f3kmgh.jpg
#spring.sendGrid.imageNext=https://res.cloudinary.com/dgwnoquie/image/upload/v1755790009/KHACH-BEP-15_bj8u43.jpg
#spring.sendGrid.logo=https://res.cloudinary.com/dgwnoquie/image/upload/v1755791051/HAUS-logo_byhum7.jpg
#
## SpringDoc OpenAPI
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true
#
## OpenAPI
#openapi.service.api-docs=Haus
#openapi.service.server=http://localhost:${server.port:8080}
#openapi.service.title=${API_TITLE:DUMMY API TITLE}
#openapi.service.version=v1.0.0
#
## Security Endpoints
#security.public-endpoints=/oauth2/**, /auth/**
#security.user-endpoints=/user/**
#security.admin-endpoints=/admin/**
#security.swagger-endpoints=/swagger-ui/**,/v3/api-docs/**,/swagger-ui.html
#
## JWT
#jwt.expiryHour=2
#jwt.expiryDay=30
#jwt.accessKey=c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
#jwt.refreshKey=9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=
#
## Cloudinary
#cloudinary.cloud_name=${CLOUDINARY_NAME}
#cloudinary.api_key=${CLOUDINARY_API_KEY}
#cloudinary.secret_key=${CLOUDINARY_SECRET_KEY}
